[2025-06-23T13:21:46.283+0000] {processor.py:186} INFO - Started process (PID=80) to work on /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:21:46.285+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_tenant_process.py for tasks to queue
[2025-06-23T13:21:46.290+0000] {logging_mixin.py:190} INFO - [2025-06-23T13:21:46.289+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:21:46.319+0000] {logging_mixin.py:190} INFO - [2025-06-23T13:21:46.315+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_tenant_process.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_tenant_process.py", line 1
    using System;
          ^^^^^^
SyntaxError: invalid syntax
[2025-06-23T13:21:46.321+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:21:46.358+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_tenant_process.py took 0.086 seconds
[2025-06-23T13:22:16.477+0000] {processor.py:186} INFO - Started process (PID=144) to work on /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:22:16.479+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_tenant_process.py for tasks to queue
[2025-06-23T13:22:16.483+0000] {logging_mixin.py:190} INFO - [2025-06-23T13:22:16.482+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:22:16.508+0000] {logging_mixin.py:190} INFO - [2025-06-23T13:22:16.506+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_tenant_process.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_tenant_process.py", line 1
    using System;
          ^^^^^^
SyntaxError: invalid syntax
[2025-06-23T13:22:16.510+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:22:16.542+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_tenant_process.py took 0.075 seconds
[2025-06-23T13:22:46.976+0000] {processor.py:186} INFO - Started process (PID=210) to work on /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:22:46.978+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_tenant_process.py for tasks to queue
[2025-06-23T13:22:46.984+0000] {logging_mixin.py:190} INFO - [2025-06-23T13:22:46.983+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:22:47.011+0000] {logging_mixin.py:190} INFO - [2025-06-23T13:22:47.009+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_tenant_process.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_tenant_process.py", line 1
    using System;
          ^^^^^^
SyntaxError: invalid syntax
[2025-06-23T13:22:47.012+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:22:47.045+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_tenant_process.py took 0.078 seconds
[2025-06-23T13:23:18.001+0000] {processor.py:186} INFO - Started process (PID=275) to work on /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:23:18.003+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_tenant_process.py for tasks to queue
[2025-06-23T13:23:18.008+0000] {logging_mixin.py:190} INFO - [2025-06-23T13:23:18.007+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:23:18.032+0000] {logging_mixin.py:190} INFO - [2025-06-23T13:23:18.031+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_tenant_process.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_tenant_process.py", line 1
    using System;
          ^^^^^^
SyntaxError: invalid syntax
[2025-06-23T13:23:18.034+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:23:18.067+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_tenant_process.py took 0.078 seconds
[2025-06-23T13:23:48.130+0000] {processor.py:186} INFO - Started process (PID=339) to work on /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:23:48.132+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_tenant_process.py for tasks to queue
[2025-06-23T13:23:48.139+0000] {logging_mixin.py:190} INFO - [2025-06-23T13:23:48.138+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:23:48.165+0000] {logging_mixin.py:190} INFO - [2025-06-23T13:23:48.162+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_tenant_process.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_tenant_process.py", line 1
    using System;
          ^^^^^^
SyntaxError: invalid syntax
[2025-06-23T13:23:48.166+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:23:48.207+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_tenant_process.py took 0.091 seconds
[2025-06-23T13:24:18.339+0000] {processor.py:186} INFO - Started process (PID=404) to work on /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:24:18.340+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_tenant_process.py for tasks to queue
[2025-06-23T13:24:18.344+0000] {logging_mixin.py:190} INFO - [2025-06-23T13:24:18.344+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:24:18.369+0000] {logging_mixin.py:190} INFO - [2025-06-23T13:24:18.367+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_tenant_process.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_tenant_process.py", line 1
    using System;
          ^^^^^^
SyntaxError: invalid syntax
[2025-06-23T13:24:18.371+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:24:18.402+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_tenant_process.py took 0.072 seconds
[2025-06-23T13:24:48.847+0000] {processor.py:186} INFO - Started process (PID=470) to work on /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:24:48.848+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_tenant_process.py for tasks to queue
[2025-06-23T13:24:48.852+0000] {logging_mixin.py:190} INFO - [2025-06-23T13:24:48.851+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:24:48.872+0000] {logging_mixin.py:190} INFO - [2025-06-23T13:24:48.870+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_tenant_process.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_tenant_process.py", line 1
    using System;
          ^^^^^^
SyntaxError: invalid syntax
[2025-06-23T13:24:48.873+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:24:48.903+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_tenant_process.py took 0.066 seconds
[2025-06-23T13:25:19.707+0000] {processor.py:186} INFO - Started process (PID=535) to work on /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:25:19.708+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_tenant_process.py for tasks to queue
[2025-06-23T13:25:19.713+0000] {logging_mixin.py:190} INFO - [2025-06-23T13:25:19.712+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:25:19.735+0000] {logging_mixin.py:190} INFO - [2025-06-23T13:25:19.734+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_tenant_process.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_tenant_process.py", line 1
    using System;
          ^^^^^^
SyntaxError: invalid syntax
[2025-06-23T13:25:19.737+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:25:19.768+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_tenant_process.py took 0.073 seconds
[2025-06-23T13:25:50.509+0000] {processor.py:186} INFO - Started process (PID=600) to work on /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:25:50.511+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_tenant_process.py for tasks to queue
[2025-06-23T13:25:50.515+0000] {logging_mixin.py:190} INFO - [2025-06-23T13:25:50.514+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:25:50.540+0000] {logging_mixin.py:190} INFO - [2025-06-23T13:25:50.538+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_tenant_process.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_tenant_process.py", line 1
    using System;
          ^^^^^^
SyntaxError: invalid syntax
[2025-06-23T13:25:50.541+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:25:50.574+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_tenant_process.py took 0.076 seconds
[2025-06-23T13:26:21.043+0000] {processor.py:186} INFO - Started process (PID=665) to work on /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:26:21.045+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_tenant_process.py for tasks to queue
[2025-06-23T13:26:21.049+0000] {logging_mixin.py:190} INFO - [2025-06-23T13:26:21.048+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:26:21.071+0000] {logging_mixin.py:190} INFO - [2025-06-23T13:26:21.069+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_tenant_process.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_tenant_process.py", line 1
    using System;
          ^^^^^^
SyntaxError: invalid syntax
[2025-06-23T13:26:21.072+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:26:21.103+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_tenant_process.py took 0.069 seconds
[2025-06-23T13:26:52.045+0000] {processor.py:186} INFO - Started process (PID=730) to work on /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:26:52.047+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_tenant_process.py for tasks to queue
[2025-06-23T13:26:52.050+0000] {logging_mixin.py:190} INFO - [2025-06-23T13:26:52.050+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:26:52.074+0000] {logging_mixin.py:190} INFO - [2025-06-23T13:26:52.072+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_tenant_process.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_tenant_process.py", line 1
    using System;
          ^^^^^^
SyntaxError: invalid syntax
[2025-06-23T13:26:52.075+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:26:52.106+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_tenant_process.py took 0.072 seconds
[2025-06-23T13:27:23.482+0000] {processor.py:186} INFO - Started process (PID=783) to work on /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:27:23.484+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_tenant_process.py for tasks to queue
[2025-06-23T13:27:23.488+0000] {logging_mixin.py:190} INFO - [2025-06-23T13:27:23.487+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:27:23.510+0000] {logging_mixin.py:190} INFO - [2025-06-23T13:27:23.509+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_tenant_process.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_tenant_process.py", line 1
    using System;
          ^^^^^^
SyntaxError: invalid syntax
[2025-06-23T13:27:23.512+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:27:23.549+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_tenant_process.py took 0.079 seconds
[2025-06-23T13:27:53.716+0000] {processor.py:186} INFO - Started process (PID=845) to work on /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:27:53.718+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_tenant_process.py for tasks to queue
[2025-06-23T13:27:53.721+0000] {logging_mixin.py:190} INFO - [2025-06-23T13:27:53.721+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:27:53.744+0000] {logging_mixin.py:190} INFO - [2025-06-23T13:27:53.741+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_tenant_process.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_tenant_process.py", line 1
    using System;
          ^^^^^^
SyntaxError: invalid syntax
[2025-06-23T13:27:53.745+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:27:53.782+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_tenant_process.py took 0.075 seconds
[2025-06-23T13:28:24.286+0000] {processor.py:186} INFO - Started process (PID=910) to work on /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:28:24.288+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_tenant_process.py for tasks to queue
[2025-06-23T13:28:24.292+0000] {logging_mixin.py:190} INFO - [2025-06-23T13:28:24.291+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:28:24.313+0000] {logging_mixin.py:190} INFO - [2025-06-23T13:28:24.311+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_tenant_process.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_tenant_process.py", line 1
    using System;
          ^^^^^^
SyntaxError: invalid syntax
[2025-06-23T13:28:24.314+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:28:24.345+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_tenant_process.py took 0.068 seconds
[2025-06-23T13:28:54.687+0000] {processor.py:186} INFO - Started process (PID=965) to work on /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:28:54.689+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_tenant_process.py for tasks to queue
[2025-06-23T13:28:54.693+0000] {logging_mixin.py:190} INFO - [2025-06-23T13:28:54.692+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:28:54.717+0000] {logging_mixin.py:190} INFO - [2025-06-23T13:28:54.715+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_tenant_process.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_tenant_process.py", line 1
    using System;
          ^^^^^^
SyntaxError: invalid syntax
[2025-06-23T13:28:54.718+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:28:54.750+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_tenant_process.py took 0.072 seconds
[2025-06-23T13:29:25.879+0000] {processor.py:186} INFO - Started process (PID=1030) to work on /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:29:25.880+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_tenant_process.py for tasks to queue
[2025-06-23T13:29:25.884+0000] {logging_mixin.py:190} INFO - [2025-06-23T13:29:25.884+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:29:25.903+0000] {logging_mixin.py:190} INFO - [2025-06-23T13:29:25.901+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_tenant_process.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_tenant_process.py", line 1
    using System;
          ^^^^^^
SyntaxError: invalid syntax
[2025-06-23T13:29:25.904+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:29:25.933+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_tenant_process.py took 0.064 seconds
[2025-06-23T13:29:56.516+0000] {processor.py:186} INFO - Started process (PID=1089) to work on /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:29:56.518+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_tenant_process.py for tasks to queue
[2025-06-23T13:29:56.521+0000] {logging_mixin.py:190} INFO - [2025-06-23T13:29:56.521+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:29:56.544+0000] {logging_mixin.py:190} INFO - [2025-06-23T13:29:56.542+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_tenant_process.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_tenant_process.py", line 1
    using System;
          ^^^^^^
SyntaxError: invalid syntax
[2025-06-23T13:29:56.545+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:29:56.578+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_tenant_process.py took 0.072 seconds
[2025-06-23T13:30:27.921+0000] {processor.py:186} INFO - Started process (PID=1154) to work on /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:30:27.922+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_tenant_process.py for tasks to queue
[2025-06-23T13:30:27.926+0000] {logging_mixin.py:190} INFO - [2025-06-23T13:30:27.926+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:30:27.951+0000] {logging_mixin.py:190} INFO - [2025-06-23T13:30:27.949+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_tenant_process.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_tenant_process.py", line 1
    using System;
          ^^^^^^
SyntaxError: invalid syntax
[2025-06-23T13:30:27.952+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:30:27.989+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_tenant_process.py took 0.081 seconds
[2025-06-23T13:30:59.024+0000] {processor.py:186} INFO - Started process (PID=1218) to work on /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:30:59.026+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_tenant_process.py for tasks to queue
[2025-06-23T13:30:59.032+0000] {logging_mixin.py:190} INFO - [2025-06-23T13:30:59.031+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:30:59.059+0000] {logging_mixin.py:190} INFO - [2025-06-23T13:30:59.056+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_tenant_process.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_tenant_process.py", line 1
    using System;
          ^^^^^^
SyntaxError: invalid syntax
[2025-06-23T13:30:59.060+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:30:59.110+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_tenant_process.py took 0.100 seconds
[2025-06-23T13:31:29.711+0000] {processor.py:186} INFO - Started process (PID=1282) to work on /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:31:29.713+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_tenant_process.py for tasks to queue
[2025-06-23T13:31:29.718+0000] {logging_mixin.py:190} INFO - [2025-06-23T13:31:29.717+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:31:29.742+0000] {logging_mixin.py:190} INFO - [2025-06-23T13:31:29.740+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_tenant_process.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_tenant_process.py", line 1
    using System;
          ^^^^^^
SyntaxError: invalid syntax
[2025-06-23T13:31:29.744+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:31:29.779+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_tenant_process.py took 0.080 seconds
[2025-06-23T13:32:00.334+0000] {processor.py:186} INFO - Started process (PID=1347) to work on /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:32:00.338+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_tenant_process.py for tasks to queue
[2025-06-23T13:32:00.346+0000] {logging_mixin.py:190} INFO - [2025-06-23T13:32:00.345+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:32:00.380+0000] {logging_mixin.py:190} INFO - [2025-06-23T13:32:00.376+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_tenant_process.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_tenant_process.py", line 1
    using System;
          ^^^^^^
SyntaxError: invalid syntax
[2025-06-23T13:32:00.381+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:32:00.420+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_tenant_process.py took 0.100 seconds
[2025-06-23T13:32:30.966+0000] {processor.py:186} INFO - Started process (PID=1412) to work on /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:32:30.968+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_tenant_process.py for tasks to queue
[2025-06-23T13:32:30.973+0000] {logging_mixin.py:190} INFO - [2025-06-23T13:32:30.972+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:32:30.997+0000] {logging_mixin.py:190} INFO - [2025-06-23T13:32:30.995+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_tenant_process.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_tenant_process.py", line 1
    using System;
          ^^^^^^
SyntaxError: invalid syntax
[2025-06-23T13:32:30.998+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:32:31.030+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_tenant_process.py took 0.077 seconds
[2025-06-23T13:33:01.326+0000] {processor.py:186} INFO - Started process (PID=1477) to work on /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:33:01.327+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_tenant_process.py for tasks to queue
[2025-06-23T13:33:01.333+0000] {logging_mixin.py:190} INFO - [2025-06-23T13:33:01.333+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:33:01.360+0000] {logging_mixin.py:190} INFO - [2025-06-23T13:33:01.358+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_tenant_process.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_tenant_process.py", line 1
    using System;
          ^^^^^^
SyntaxError: invalid syntax
[2025-06-23T13:33:01.362+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:33:01.397+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_tenant_process.py took 0.080 seconds
[2025-06-23T13:33:31.836+0000] {processor.py:186} INFO - Started process (PID=1542) to work on /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:33:31.838+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_tenant_process.py for tasks to queue
[2025-06-23T13:33:31.842+0000] {logging_mixin.py:190} INFO - [2025-06-23T13:33:31.842+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:33:31.864+0000] {logging_mixin.py:190} INFO - [2025-06-23T13:33:31.862+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_tenant_process.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_tenant_process.py", line 1
    using System;
          ^^^^^^
SyntaxError: invalid syntax
[2025-06-23T13:33:31.865+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:33:31.894+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_tenant_process.py took 0.067 seconds
[2025-06-23T13:34:02.563+0000] {processor.py:186} INFO - Started process (PID=1607) to work on /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:34:02.565+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_tenant_process.py for tasks to queue
[2025-06-23T13:34:02.569+0000] {logging_mixin.py:190} INFO - [2025-06-23T13:34:02.568+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:34:02.589+0000] {logging_mixin.py:190} INFO - [2025-06-23T13:34:02.587+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_tenant_process.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_tenant_process.py", line 1
    using System;
          ^^^^^^
SyntaxError: invalid syntax
[2025-06-23T13:34:02.590+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:34:02.618+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_tenant_process.py took 0.065 seconds
[2025-06-23T13:34:33.212+0000] {processor.py:186} INFO - Started process (PID=1672) to work on /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:34:33.214+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_tenant_process.py for tasks to queue
[2025-06-23T13:34:33.218+0000] {logging_mixin.py:190} INFO - [2025-06-23T13:34:33.218+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:34:33.241+0000] {logging_mixin.py:190} INFO - [2025-06-23T13:34:33.240+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_tenant_process.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_tenant_process.py", line 1
    using System;
          ^^^^^^
SyntaxError: invalid syntax
[2025-06-23T13:34:33.243+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:34:33.272+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_tenant_process.py took 0.068 seconds
[2025-06-23T13:35:03.768+0000] {processor.py:186} INFO - Started process (PID=1737) to work on /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:35:03.771+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_tenant_process.py for tasks to queue
[2025-06-23T13:35:03.776+0000] {logging_mixin.py:190} INFO - [2025-06-23T13:35:03.776+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:35:03.800+0000] {logging_mixin.py:190} INFO - [2025-06-23T13:35:03.798+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_tenant_process.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_tenant_process.py", line 1
    using System;
          ^^^^^^
SyntaxError: invalid syntax
[2025-06-23T13:35:03.801+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:35:03.837+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_tenant_process.py took 0.080 seconds
[2025-06-23T13:35:33.997+0000] {processor.py:186} INFO - Started process (PID=1802) to work on /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:35:33.999+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_tenant_process.py for tasks to queue
[2025-06-23T13:35:34.002+0000] {logging_mixin.py:190} INFO - [2025-06-23T13:35:34.002+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:35:34.022+0000] {logging_mixin.py:190} INFO - [2025-06-23T13:35:34.021+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_tenant_process.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_tenant_process.py", line 1
    using System;
          ^^^^^^
SyntaxError: invalid syntax
[2025-06-23T13:35:34.024+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:35:34.052+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_tenant_process.py took 0.064 seconds
[2025-06-23T13:36:04.451+0000] {processor.py:186} INFO - Started process (PID=1868) to work on /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:36:04.452+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_tenant_process.py for tasks to queue
[2025-06-23T13:36:04.456+0000] {logging_mixin.py:190} INFO - [2025-06-23T13:36:04.455+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:36:04.476+0000] {logging_mixin.py:190} INFO - [2025-06-23T13:36:04.474+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_tenant_process.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_tenant_process.py", line 1
    using System;
          ^^^^^^
SyntaxError: invalid syntax
[2025-06-23T13:36:04.477+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:36:04.505+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_tenant_process.py took 0.063 seconds
[2025-06-23T13:36:44.620+0000] {processor.py:186} INFO - Started process (PID=1939) to work on /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:36:44.622+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_tenant_process.py for tasks to queue
[2025-06-23T13:36:44.625+0000] {logging_mixin.py:190} INFO - [2025-06-23T13:36:44.625+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:36:44.648+0000] {logging_mixin.py:190} INFO - [2025-06-23T13:36:44.646+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_tenant_process.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_tenant_process.py", line 1
    using System;
          ^^^^^^
SyntaxError: invalid syntax
[2025-06-23T13:36:44.649+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:36:44.678+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_tenant_process.py took 0.068 seconds
[2025-06-23T13:37:15.642+0000] {processor.py:186} INFO - Started process (PID=2004) to work on /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:37:15.644+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_tenant_process.py for tasks to queue
[2025-06-23T13:37:15.647+0000] {logging_mixin.py:190} INFO - [2025-06-23T13:37:15.647+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:37:15.669+0000] {logging_mixin.py:190} INFO - [2025-06-23T13:37:15.667+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_tenant_process.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_tenant_process.py", line 1
    using System;
          ^^^^^^
SyntaxError: invalid syntax
[2025-06-23T13:37:15.670+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:37:15.699+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_tenant_process.py took 0.067 seconds
[2025-06-23T13:37:46.182+0000] {processor.py:186} INFO - Started process (PID=2069) to work on /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:37:46.183+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_tenant_process.py for tasks to queue
[2025-06-23T13:37:46.188+0000] {logging_mixin.py:190} INFO - [2025-06-23T13:37:46.187+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:37:46.211+0000] {logging_mixin.py:190} INFO - [2025-06-23T13:37:46.209+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_tenant_process.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_tenant_process.py", line 1
    using System;
          ^^^^^^
SyntaxError: invalid syntax
[2025-06-23T13:37:46.212+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:37:46.244+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_tenant_process.py took 0.075 seconds
[2025-06-23T13:38:17.241+0000] {processor.py:186} INFO - Started process (PID=2134) to work on /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:38:17.243+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_tenant_process.py for tasks to queue
[2025-06-23T13:38:17.248+0000] {logging_mixin.py:190} INFO - [2025-06-23T13:38:17.247+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:38:17.271+0000] {logging_mixin.py:190} INFO - [2025-06-23T13:38:17.269+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_tenant_process.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_tenant_process.py", line 1
    using System;
          ^^^^^^
SyntaxError: invalid syntax
[2025-06-23T13:38:17.272+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:38:17.302+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_tenant_process.py took 0.070 seconds
[2025-06-23T13:38:47.922+0000] {processor.py:186} INFO - Started process (PID=2199) to work on /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:38:47.923+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_tenant_process.py for tasks to queue
[2025-06-23T13:38:47.928+0000] {logging_mixin.py:190} INFO - [2025-06-23T13:38:47.928+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:38:47.949+0000] {logging_mixin.py:190} INFO - [2025-06-23T13:38:47.947+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_tenant_process.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_tenant_process.py", line 1
    using System;
          ^^^^^^
SyntaxError: invalid syntax
[2025-06-23T13:38:47.950+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:38:47.978+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_tenant_process.py took 0.064 seconds
[2025-06-23T13:39:18.052+0000] {processor.py:186} INFO - Started process (PID=2263) to work on /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:39:18.054+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_tenant_process.py for tasks to queue
[2025-06-23T13:39:18.058+0000] {logging_mixin.py:190} INFO - [2025-06-23T13:39:18.057+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:39:18.079+0000] {logging_mixin.py:190} INFO - [2025-06-23T13:39:18.078+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_tenant_process.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_tenant_process.py", line 1
    using System;
          ^^^^^^
SyntaxError: invalid syntax
[2025-06-23T13:39:18.080+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:39:18.110+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_tenant_process.py took 0.066 seconds
[2025-06-23T13:39:48.378+0000] {processor.py:186} INFO - Started process (PID=2329) to work on /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:39:48.380+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_tenant_process.py for tasks to queue
[2025-06-23T13:39:48.385+0000] {logging_mixin.py:190} INFO - [2025-06-23T13:39:48.384+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:39:48.408+0000] {logging_mixin.py:190} INFO - [2025-06-23T13:39:48.407+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_tenant_process.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_tenant_process.py", line 1
    using System;
          ^^^^^^
SyntaxError: invalid syntax
[2025-06-23T13:39:48.409+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:39:48.440+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_tenant_process.py took 0.072 seconds
[2025-06-23T13:40:18.664+0000] {processor.py:186} INFO - Started process (PID=2394) to work on /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:40:18.665+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_tenant_process.py for tasks to queue
[2025-06-23T13:40:18.670+0000] {logging_mixin.py:190} INFO - [2025-06-23T13:40:18.669+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:40:18.688+0000] {logging_mixin.py:190} INFO - [2025-06-23T13:40:18.686+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_tenant_process.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_tenant_process.py", line 1
    using System;
          ^^^^^^
SyntaxError: invalid syntax
[2025-06-23T13:40:18.689+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:40:18.716+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_tenant_process.py took 0.061 seconds
[2025-06-23T13:40:49.010+0000] {processor.py:186} INFO - Started process (PID=2459) to work on /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:40:49.012+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_tenant_process.py for tasks to queue
[2025-06-23T13:40:49.016+0000] {logging_mixin.py:190} INFO - [2025-06-23T13:40:49.015+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:40:49.038+0000] {logging_mixin.py:190} INFO - [2025-06-23T13:40:49.036+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_tenant_process.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_tenant_process.py", line 1
    using System;
          ^^^^^^
SyntaxError: invalid syntax
[2025-06-23T13:40:49.039+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:40:49.074+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_tenant_process.py took 0.074 seconds
[2025-06-23T13:41:19.159+0000] {processor.py:186} INFO - Started process (PID=2523) to work on /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:41:19.161+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_tenant_process.py for tasks to queue
[2025-06-23T13:41:19.165+0000] {logging_mixin.py:190} INFO - [2025-06-23T13:41:19.165+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:41:19.187+0000] {logging_mixin.py:190} INFO - [2025-06-23T13:41:19.185+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_tenant_process.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_tenant_process.py", line 1
    using System;
          ^^^^^^
SyntaxError: invalid syntax
[2025-06-23T13:41:19.188+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:41:19.220+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_tenant_process.py took 0.072 seconds
[2025-06-23T13:41:50.150+0000] {processor.py:186} INFO - Started process (PID=2589) to work on /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:41:50.152+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_tenant_process.py for tasks to queue
[2025-06-23T13:41:50.155+0000] {logging_mixin.py:190} INFO - [2025-06-23T13:41:50.155+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:41:50.175+0000] {logging_mixin.py:190} INFO - [2025-06-23T13:41:50.173+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_tenant_process.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_tenant_process.py", line 1
    using System;
          ^^^^^^
SyntaxError: invalid syntax
[2025-06-23T13:41:50.176+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:41:50.207+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_tenant_process.py took 0.066 seconds
[2025-06-23T13:42:20.872+0000] {processor.py:186} INFO - Started process (PID=2654) to work on /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:42:20.873+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_tenant_process.py for tasks to queue
[2025-06-23T13:42:20.877+0000] {logging_mixin.py:190} INFO - [2025-06-23T13:42:20.876+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:42:20.895+0000] {logging_mixin.py:190} INFO - [2025-06-23T13:42:20.893+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_tenant_process.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_tenant_process.py", line 1
    using System;
          ^^^^^^
SyntaxError: invalid syntax
[2025-06-23T13:42:20.896+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:42:20.924+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_tenant_process.py took 0.061 seconds
[2025-06-23T13:42:51.514+0000] {processor.py:186} INFO - Started process (PID=2719) to work on /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:42:51.516+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_tenant_process.py for tasks to queue
[2025-06-23T13:42:51.520+0000] {logging_mixin.py:190} INFO - [2025-06-23T13:42:51.519+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:42:51.542+0000] {logging_mixin.py:190} INFO - [2025-06-23T13:42:51.540+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_tenant_process.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_tenant_process.py", line 1
    using System;
          ^^^^^^
SyntaxError: invalid syntax
[2025-06-23T13:42:51.543+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:42:51.576+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_tenant_process.py took 0.072 seconds
[2025-06-23T13:43:22.664+0000] {processor.py:186} INFO - Started process (PID=2784) to work on /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:43:22.666+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_tenant_process.py for tasks to queue
[2025-06-23T13:43:22.671+0000] {logging_mixin.py:190} INFO - [2025-06-23T13:43:22.670+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:43:22.692+0000] {logging_mixin.py:190} INFO - [2025-06-23T13:43:22.691+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_tenant_process.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_tenant_process.py", line 1
    using System;
          ^^^^^^
SyntaxError: invalid syntax
[2025-06-23T13:43:22.694+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:43:22.726+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_tenant_process.py took 0.073 seconds
[2025-06-23T13:43:53.211+0000] {processor.py:186} INFO - Started process (PID=2849) to work on /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:43:53.212+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_tenant_process.py for tasks to queue
[2025-06-23T13:43:53.216+0000] {logging_mixin.py:190} INFO - [2025-06-23T13:43:53.216+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:43:53.236+0000] {logging_mixin.py:190} INFO - [2025-06-23T13:43:53.235+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_tenant_process.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_tenant_process.py", line 1
    using System;
          ^^^^^^
SyntaxError: invalid syntax
[2025-06-23T13:43:53.238+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:43:53.267+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_tenant_process.py took 0.067 seconds
[2025-06-23T13:44:23.562+0000] {processor.py:186} INFO - Started process (PID=2913) to work on /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:44:23.563+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_tenant_process.py for tasks to queue
[2025-06-23T13:44:23.567+0000] {logging_mixin.py:190} INFO - [2025-06-23T13:44:23.566+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:44:23.590+0000] {logging_mixin.py:190} INFO - [2025-06-23T13:44:23.587+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_tenant_process.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_tenant_process.py", line 1
    using System;
          ^^^^^^
SyntaxError: invalid syntax
[2025-06-23T13:44:23.591+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:44:23.626+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_tenant_process.py took 0.074 seconds
[2025-06-23T13:44:54.355+0000] {processor.py:186} INFO - Started process (PID=2978) to work on /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:44:54.356+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_tenant_process.py for tasks to queue
[2025-06-23T13:44:54.361+0000] {logging_mixin.py:190} INFO - [2025-06-23T13:44:54.360+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:44:54.382+0000] {logging_mixin.py:190} INFO - [2025-06-23T13:44:54.380+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_tenant_process.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_tenant_process.py", line 1
    using System;
          ^^^^^^
SyntaxError: invalid syntax
[2025-06-23T13:44:54.383+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:44:54.411+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_tenant_process.py took 0.065 seconds
[2025-06-23T13:45:25.286+0000] {processor.py:186} INFO - Started process (PID=3043) to work on /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:45:25.287+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_tenant_process.py for tasks to queue
[2025-06-23T13:45:25.292+0000] {logging_mixin.py:190} INFO - [2025-06-23T13:45:25.291+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:45:25.313+0000] {logging_mixin.py:190} INFO - [2025-06-23T13:45:25.311+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_tenant_process.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_tenant_process.py", line 1
    using System;
          ^^^^^^
SyntaxError: invalid syntax
[2025-06-23T13:45:25.314+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:45:25.344+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_tenant_process.py took 0.068 seconds
[2025-06-23T13:45:55.618+0000] {processor.py:186} INFO - Started process (PID=3108) to work on /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:45:55.619+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_tenant_process.py for tasks to queue
[2025-06-23T13:45:55.623+0000] {logging_mixin.py:190} INFO - [2025-06-23T13:45:55.622+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:45:55.646+0000] {logging_mixin.py:190} INFO - [2025-06-23T13:45:55.644+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_tenant_process.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_tenant_process.py", line 1
    using System;
          ^^^^^^
SyntaxError: invalid syntax
[2025-06-23T13:45:55.647+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:45:55.676+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_tenant_process.py took 0.068 seconds
[2025-06-23T13:46:25.992+0000] {processor.py:186} INFO - Started process (PID=3173) to work on /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:46:25.994+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_tenant_process.py for tasks to queue
[2025-06-23T13:46:25.999+0000] {logging_mixin.py:190} INFO - [2025-06-23T13:46:25.998+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:46:26.025+0000] {logging_mixin.py:190} INFO - [2025-06-23T13:46:26.023+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_tenant_process.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_tenant_process.py", line 1
    using System;
          ^^^^^^
SyntaxError: invalid syntax
[2025-06-23T13:46:26.027+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:46:26.061+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_tenant_process.py took 0.081 seconds
[2025-06-23T13:46:56.471+0000] {processor.py:186} INFO - Started process (PID=3239) to work on /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:46:56.472+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_tenant_process.py for tasks to queue
[2025-06-23T13:46:56.476+0000] {logging_mixin.py:190} INFO - [2025-06-23T13:46:56.476+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:46:56.499+0000] {logging_mixin.py:190} INFO - [2025-06-23T13:46:56.496+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_tenant_process.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_tenant_process.py", line 1
    using System;
          ^^^^^^
SyntaxError: invalid syntax
[2025-06-23T13:46:56.500+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:46:56.527+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_tenant_process.py took 0.066 seconds
[2025-06-23T13:47:26.984+0000] {processor.py:186} INFO - Started process (PID=3304) to work on /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:47:26.986+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_tenant_process.py for tasks to queue
[2025-06-23T13:47:26.991+0000] {logging_mixin.py:190} INFO - [2025-06-23T13:47:26.990+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:47:27.012+0000] {logging_mixin.py:190} INFO - [2025-06-23T13:47:27.010+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_tenant_process.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_tenant_process.py", line 1
    using System;
          ^^^^^^
SyntaxError: invalid syntax
[2025-06-23T13:47:27.013+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:47:27.044+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_tenant_process.py took 0.071 seconds
[2025-06-23T13:47:57.747+0000] {processor.py:186} INFO - Started process (PID=3369) to work on /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:47:57.749+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_tenant_process.py for tasks to queue
[2025-06-23T13:47:57.755+0000] {logging_mixin.py:190} INFO - [2025-06-23T13:47:57.754+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:47:57.783+0000] {logging_mixin.py:190} INFO - [2025-06-23T13:47:57.781+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_tenant_process.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_tenant_process.py", line 1
    using System;
          ^^^^^^
SyntaxError: invalid syntax
[2025-06-23T13:47:57.785+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:47:57.827+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_tenant_process.py took 0.089 seconds
[2025-06-23T13:48:28.259+0000] {processor.py:186} INFO - Started process (PID=3434) to work on /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:48:28.261+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_tenant_process.py for tasks to queue
[2025-06-23T13:48:28.265+0000] {logging_mixin.py:190} INFO - [2025-06-23T13:48:28.264+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:48:28.287+0000] {logging_mixin.py:190} INFO - [2025-06-23T13:48:28.285+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_tenant_process.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_tenant_process.py", line 1
    using System;
          ^^^^^^
SyntaxError: invalid syntax
[2025-06-23T13:48:28.288+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:48:28.318+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_tenant_process.py took 0.068 seconds
[2025-06-23T13:48:58.729+0000] {processor.py:186} INFO - Started process (PID=3499) to work on /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:48:58.731+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_tenant_process.py for tasks to queue
[2025-06-23T13:48:58.736+0000] {logging_mixin.py:190} INFO - [2025-06-23T13:48:58.735+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:48:58.763+0000] {logging_mixin.py:190} INFO - [2025-06-23T13:48:58.760+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_tenant_process.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_tenant_process.py", line 1
    using System;
          ^^^^^^
SyntaxError: invalid syntax
[2025-06-23T13:48:58.765+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:48:58.799+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_tenant_process.py took 0.083 seconds
[2025-06-23T13:49:29.621+0000] {processor.py:186} INFO - Started process (PID=3564) to work on /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:49:29.622+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_tenant_process.py for tasks to queue
[2025-06-23T13:49:29.626+0000] {logging_mixin.py:190} INFO - [2025-06-23T13:49:29.626+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:49:29.645+0000] {logging_mixin.py:190} INFO - [2025-06-23T13:49:29.643+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_tenant_process.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_tenant_process.py", line 1
    using System;
          ^^^^^^
SyntaxError: invalid syntax
[2025-06-23T13:49:29.646+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:49:29.676+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_tenant_process.py took 0.064 seconds
[2025-06-23T13:50:00.364+0000] {processor.py:186} INFO - Started process (PID=3629) to work on /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:50:00.366+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_tenant_process.py for tasks to queue
[2025-06-23T13:50:00.369+0000] {logging_mixin.py:190} INFO - [2025-06-23T13:50:00.369+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:50:00.391+0000] {logging_mixin.py:190} INFO - [2025-06-23T13:50:00.389+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_tenant_process.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_tenant_process.py", line 1
    using System;
          ^^^^^^
SyntaxError: invalid syntax
[2025-06-23T13:50:00.393+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:50:00.422+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_tenant_process.py took 0.068 seconds
[2025-06-23T13:50:30.739+0000] {processor.py:186} INFO - Started process (PID=3694) to work on /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:50:30.741+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_tenant_process.py for tasks to queue
[2025-06-23T13:50:30.744+0000] {logging_mixin.py:190} INFO - [2025-06-23T13:50:30.744+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:50:30.767+0000] {logging_mixin.py:190} INFO - [2025-06-23T13:50:30.765+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_tenant_process.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_tenant_process.py", line 1
    using System;
          ^^^^^^
SyntaxError: invalid syntax
[2025-06-23T13:50:30.768+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:50:30.798+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_tenant_process.py took 0.068 seconds
[2025-06-23T13:51:01.323+0000] {processor.py:186} INFO - Started process (PID=3759) to work on /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:51:01.325+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_tenant_process.py for tasks to queue
[2025-06-23T13:51:01.328+0000] {logging_mixin.py:190} INFO - [2025-06-23T13:51:01.328+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:51:01.351+0000] {logging_mixin.py:190} INFO - [2025-06-23T13:51:01.349+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_tenant_process.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_tenant_process.py", line 1
    using System;
          ^^^^^^
SyntaxError: invalid syntax
[2025-06-23T13:51:01.352+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:51:01.385+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_tenant_process.py took 0.071 seconds
[2025-06-23T13:51:32.169+0000] {processor.py:186} INFO - Started process (PID=3820) to work on /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:51:32.171+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_tenant_process.py for tasks to queue
[2025-06-23T13:51:32.175+0000] {logging_mixin.py:190} INFO - [2025-06-23T13:51:32.174+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:51:32.195+0000] {logging_mixin.py:190} INFO - [2025-06-23T13:51:32.194+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_tenant_process.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_tenant_process.py", line 1
    using System;
          ^^^^^^
SyntaxError: invalid syntax
[2025-06-23T13:51:32.196+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:51:32.227+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_tenant_process.py took 0.069 seconds
[2025-06-23T13:52:02.683+0000] {processor.py:186} INFO - Started process (PID=3880) to work on /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:52:02.685+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_tenant_process.py for tasks to queue
[2025-06-23T13:52:02.690+0000] {logging_mixin.py:190} INFO - [2025-06-23T13:52:02.689+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:52:02.709+0000] {logging_mixin.py:190} INFO - [2025-06-23T13:52:02.707+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_tenant_process.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_tenant_process.py", line 1
    using System;
          ^^^^^^
SyntaxError: invalid syntax
[2025-06-23T13:52:02.710+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:52:02.738+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_tenant_process.py took 0.067 seconds
[2025-06-23T13:52:33.413+0000] {processor.py:186} INFO - Started process (PID=3946) to work on /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:52:33.414+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_tenant_process.py for tasks to queue
[2025-06-23T13:52:33.419+0000] {logging_mixin.py:190} INFO - [2025-06-23T13:52:33.418+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:52:33.441+0000] {logging_mixin.py:190} INFO - [2025-06-23T13:52:33.439+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_tenant_process.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_tenant_process.py", line 1
    using System;
          ^^^^^^
SyntaxError: invalid syntax
[2025-06-23T13:52:33.442+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:52:33.472+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_tenant_process.py took 0.070 seconds
[2025-06-23T13:53:03.649+0000] {processor.py:186} INFO - Started process (PID=4011) to work on /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:53:03.650+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_tenant_process.py for tasks to queue
[2025-06-23T13:53:03.655+0000] {logging_mixin.py:190} INFO - [2025-06-23T13:53:03.655+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:53:03.680+0000] {logging_mixin.py:190} INFO - [2025-06-23T13:53:03.678+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_tenant_process.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_tenant_process.py", line 1
    using System;
          ^^^^^^
SyntaxError: invalid syntax
[2025-06-23T13:53:03.681+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:53:03.712+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_tenant_process.py took 0.074 seconds
[2025-06-23T13:53:33.960+0000] {processor.py:186} INFO - Started process (PID=4076) to work on /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:53:33.961+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_tenant_process.py for tasks to queue
[2025-06-23T13:53:33.966+0000] {logging_mixin.py:190} INFO - [2025-06-23T13:53:33.965+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:53:33.985+0000] {logging_mixin.py:190} INFO - [2025-06-23T13:53:33.983+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_tenant_process.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_tenant_process.py", line 1
    using System;
          ^^^^^^
SyntaxError: invalid syntax
[2025-06-23T13:53:33.986+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:53:34.012+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_tenant_process.py took 0.063 seconds
[2025-06-23T13:54:04.280+0000] {processor.py:186} INFO - Started process (PID=4140) to work on /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:54:04.282+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_tenant_process.py for tasks to queue
[2025-06-23T13:54:04.286+0000] {logging_mixin.py:190} INFO - [2025-06-23T13:54:04.286+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:54:04.308+0000] {logging_mixin.py:190} INFO - [2025-06-23T13:54:04.306+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_tenant_process.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_tenant_process.py", line 1
    using System;
          ^^^^^^
SyntaxError: invalid syntax
[2025-06-23T13:54:04.310+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:54:04.344+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_tenant_process.py took 0.075 seconds
[2025-06-23T13:54:34.535+0000] {processor.py:186} INFO - Started process (PID=4205) to work on /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:54:34.537+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_tenant_process.py for tasks to queue
[2025-06-23T13:54:34.542+0000] {logging_mixin.py:190} INFO - [2025-06-23T13:54:34.541+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:54:34.563+0000] {logging_mixin.py:190} INFO - [2025-06-23T13:54:34.561+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_tenant_process.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_tenant_process.py", line 1
    using System;
          ^^^^^^
SyntaxError: invalid syntax
[2025-06-23T13:54:34.565+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:54:34.596+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_tenant_process.py took 0.073 seconds
[2025-06-23T13:55:04.942+0000] {processor.py:186} INFO - Started process (PID=4271) to work on /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:55:04.943+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_tenant_process.py for tasks to queue
[2025-06-23T13:55:04.948+0000] {logging_mixin.py:190} INFO - [2025-06-23T13:55:04.947+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:55:04.969+0000] {logging_mixin.py:190} INFO - [2025-06-23T13:55:04.967+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_tenant_process.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_tenant_process.py", line 1
    using System;
          ^^^^^^
SyntaxError: invalid syntax
[2025-06-23T13:55:04.971+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:55:05.001+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_tenant_process.py took 0.069 seconds
[2025-06-23T13:55:35.215+0000] {processor.py:186} INFO - Started process (PID=4335) to work on /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:55:35.217+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_tenant_process.py for tasks to queue
[2025-06-23T13:55:35.221+0000] {logging_mixin.py:190} INFO - [2025-06-23T13:55:35.221+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:55:35.243+0000] {logging_mixin.py:190} INFO - [2025-06-23T13:55:35.240+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_tenant_process.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_tenant_process.py", line 1
    using System;
          ^^^^^^
SyntaxError: invalid syntax
[2025-06-23T13:55:35.244+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:55:35.275+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_tenant_process.py took 0.069 seconds
[2025-06-23T13:56:06.232+0000] {processor.py:186} INFO - Started process (PID=4400) to work on /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:56:06.234+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_tenant_process.py for tasks to queue
[2025-06-23T13:56:06.238+0000] {logging_mixin.py:190} INFO - [2025-06-23T13:56:06.237+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:56:06.259+0000] {logging_mixin.py:190} INFO - [2025-06-23T13:56:06.258+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_tenant_process.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_tenant_process.py", line 1
    using System;
          ^^^^^^
SyntaxError: invalid syntax
[2025-06-23T13:56:06.260+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:56:06.290+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_tenant_process.py took 0.067 seconds
[2025-06-23T13:56:46.812+0000] {processor.py:186} INFO - Started process (PID=4471) to work on /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:56:46.813+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_tenant_process.py for tasks to queue
[2025-06-23T13:56:46.817+0000] {logging_mixin.py:190} INFO - [2025-06-23T13:56:46.816+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:56:46.838+0000] {logging_mixin.py:190} INFO - [2025-06-23T13:56:46.836+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_tenant_process.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_tenant_process.py", line 1
    using System;
          ^^^^^^
SyntaxError: invalid syntax
[2025-06-23T13:56:46.839+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:56:46.872+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_tenant_process.py took 0.069 seconds
[2025-06-23T13:57:17.392+0000] {processor.py:186} INFO - Started process (PID=4536) to work on /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:57:17.394+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_tenant_process.py for tasks to queue
[2025-06-23T13:57:17.398+0000] {logging_mixin.py:190} INFO - [2025-06-23T13:57:17.398+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:57:17.422+0000] {logging_mixin.py:190} INFO - [2025-06-23T13:57:17.419+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_tenant_process.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_tenant_process.py", line 1
    using System;
          ^^^^^^
SyntaxError: invalid syntax
[2025-06-23T13:57:17.423+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:57:17.456+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_tenant_process.py took 0.075 seconds
[2025-06-23T13:57:47.566+0000] {processor.py:186} INFO - Started process (PID=4600) to work on /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:57:47.568+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_tenant_process.py for tasks to queue
[2025-06-23T13:57:47.573+0000] {logging_mixin.py:190} INFO - [2025-06-23T13:57:47.572+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:57:47.595+0000] {logging_mixin.py:190} INFO - [2025-06-23T13:57:47.593+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_tenant_process.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_tenant_process.py", line 1
    using System;
          ^^^^^^
SyntaxError: invalid syntax
[2025-06-23T13:57:47.596+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:57:47.632+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_tenant_process.py took 0.082 seconds
[2025-06-23T13:58:17.753+0000] {processor.py:186} INFO - Started process (PID=4665) to work on /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:58:17.755+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_tenant_process.py for tasks to queue
[2025-06-23T13:58:17.759+0000] {logging_mixin.py:190} INFO - [2025-06-23T13:58:17.758+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:58:17.777+0000] {logging_mixin.py:190} INFO - [2025-06-23T13:58:17.775+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_tenant_process.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_tenant_process.py", line 1
    using System;
          ^^^^^^
SyntaxError: invalid syntax
[2025-06-23T13:58:17.778+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:58:17.809+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_tenant_process.py took 0.067 seconds
[2025-06-23T13:58:48.250+0000] {processor.py:186} INFO - Started process (PID=4730) to work on /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:58:48.252+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_tenant_process.py for tasks to queue
[2025-06-23T13:58:48.256+0000] {logging_mixin.py:190} INFO - [2025-06-23T13:58:48.255+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:58:48.278+0000] {logging_mixin.py:190} INFO - [2025-06-23T13:58:48.276+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_tenant_process.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_tenant_process.py", line 1
    using System;
          ^^^^^^
SyntaxError: invalid syntax
[2025-06-23T13:58:48.279+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:58:48.313+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_tenant_process.py took 0.075 seconds
[2025-06-23T13:59:18.667+0000] {processor.py:186} INFO - Started process (PID=4795) to work on /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:59:18.669+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_tenant_process.py for tasks to queue
[2025-06-23T13:59:18.672+0000] {logging_mixin.py:190} INFO - [2025-06-23T13:59:18.672+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:59:18.690+0000] {logging_mixin.py:190} INFO - [2025-06-23T13:59:18.688+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_tenant_process.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_tenant_process.py", line 1
    using System;
          ^^^^^^
SyntaxError: invalid syntax
[2025-06-23T13:59:18.692+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:59:18.723+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_tenant_process.py took 0.067 seconds
[2025-06-23T13:59:48.844+0000] {processor.py:186} INFO - Started process (PID=4860) to work on /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:59:48.849+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_tenant_process.py for tasks to queue
[2025-06-23T13:59:48.869+0000] {logging_mixin.py:190} INFO - [2025-06-23T13:59:48.868+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:59:48.888+0000] {logging_mixin.py:190} INFO - [2025-06-23T13:59:48.887+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_tenant_process.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_tenant_process.py", line 1
    using System;
          ^^^^^^
SyntaxError: invalid syntax
[2025-06-23T13:59:48.889+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T13:59:48.918+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_tenant_process.py took 0.114 seconds
[2025-06-23T14:00:19.130+0000] {processor.py:186} INFO - Started process (PID=4925) to work on /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T14:00:19.132+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_tenant_process.py for tasks to queue
[2025-06-23T14:00:19.137+0000] {logging_mixin.py:190} INFO - [2025-06-23T14:00:19.136+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T14:00:19.158+0000] {logging_mixin.py:190} INFO - [2025-06-23T14:00:19.156+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_tenant_process.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_tenant_process.py", line 1
    using System;
          ^^^^^^
SyntaxError: invalid syntax
[2025-06-23T14:00:19.159+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T14:00:19.190+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_tenant_process.py took 0.070 seconds
[2025-06-23T14:00:49.785+0000] {processor.py:186} INFO - Started process (PID=4990) to work on /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T14:00:49.788+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_tenant_process.py for tasks to queue
[2025-06-23T14:00:49.796+0000] {logging_mixin.py:190} INFO - [2025-06-23T14:00:49.795+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T14:00:49.821+0000] {logging_mixin.py:190} INFO - [2025-06-23T14:00:49.818+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_tenant_process.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_tenant_process.py", line 1
    using System;
          ^^^^^^
SyntaxError: invalid syntax
[2025-06-23T14:00:49.822+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T14:00:49.861+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_tenant_process.py took 0.091 seconds
[2025-06-23T14:01:20.071+0000] {processor.py:186} INFO - Started process (PID=5055) to work on /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T14:01:20.073+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_tenant_process.py for tasks to queue
[2025-06-23T14:01:20.078+0000] {logging_mixin.py:190} INFO - [2025-06-23T14:01:20.077+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T14:01:20.102+0000] {logging_mixin.py:190} INFO - [2025-06-23T14:01:20.100+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_tenant_process.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_tenant_process.py", line 1
    using System;
          ^^^^^^
SyntaxError: invalid syntax
[2025-06-23T14:01:20.103+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T14:01:20.138+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_tenant_process.py took 0.078 seconds
[2025-06-23T14:01:50.983+0000] {processor.py:186} INFO - Started process (PID=5120) to work on /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T14:01:50.985+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_tenant_process.py for tasks to queue
[2025-06-23T14:01:50.988+0000] {logging_mixin.py:190} INFO - [2025-06-23T14:01:50.988+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T14:01:51.010+0000] {logging_mixin.py:190} INFO - [2025-06-23T14:01:51.008+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_tenant_process.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_tenant_process.py", line 1
    using System;
          ^^^^^^
SyntaxError: invalid syntax
[2025-06-23T14:01:51.011+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T14:01:51.042+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_tenant_process.py took 0.069 seconds
[2025-06-23T14:02:21.254+0000] {processor.py:186} INFO - Started process (PID=5185) to work on /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T14:02:21.256+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_tenant_process.py for tasks to queue
[2025-06-23T14:02:21.260+0000] {logging_mixin.py:190} INFO - [2025-06-23T14:02:21.259+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T14:02:21.278+0000] {logging_mixin.py:190} INFO - [2025-06-23T14:02:21.276+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_tenant_process.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_tenant_process.py", line 1
    using System;
          ^^^^^^
SyntaxError: invalid syntax
[2025-06-23T14:02:21.279+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T14:02:21.308+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_tenant_process.py took 0.063 seconds
[2025-06-23T14:02:51.856+0000] {processor.py:186} INFO - Started process (PID=5250) to work on /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T14:02:51.858+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_tenant_process.py for tasks to queue
[2025-06-23T14:02:51.862+0000] {logging_mixin.py:190} INFO - [2025-06-23T14:02:51.861+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T14:02:51.881+0000] {logging_mixin.py:190} INFO - [2025-06-23T14:02:51.879+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_tenant_process.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_tenant_process.py", line 1
    using System;
          ^^^^^^
SyntaxError: invalid syntax
[2025-06-23T14:02:51.882+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T14:02:51.912+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_tenant_process.py took 0.067 seconds
[2025-06-23T14:03:22.041+0000] {processor.py:186} INFO - Started process (PID=5315) to work on /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T14:03:22.043+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_tenant_process.py for tasks to queue
[2025-06-23T14:03:22.047+0000] {logging_mixin.py:190} INFO - [2025-06-23T14:03:22.046+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T14:03:22.065+0000] {logging_mixin.py:190} INFO - [2025-06-23T14:03:22.064+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_tenant_process.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_tenant_process.py", line 1
    using System;
          ^^^^^^
SyntaxError: invalid syntax
[2025-06-23T14:03:22.067+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T14:03:22.097+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_tenant_process.py took 0.067 seconds
[2025-06-23T14:03:52.192+0000] {processor.py:186} INFO - Started process (PID=5378) to work on /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T14:03:52.194+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_tenant_process.py for tasks to queue
[2025-06-23T14:03:52.198+0000] {logging_mixin.py:190} INFO - [2025-06-23T14:03:52.197+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T14:03:52.218+0000] {logging_mixin.py:190} INFO - [2025-06-23T14:03:52.216+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_tenant_process.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_tenant_process.py", line 1
    using System;
          ^^^^^^
SyntaxError: invalid syntax
[2025-06-23T14:03:52.219+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T14:03:52.254+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_tenant_process.py took 0.072 seconds
[2025-06-23T14:04:22.442+0000] {processor.py:186} INFO - Started process (PID=5442) to work on /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T14:04:22.443+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_tenant_process.py for tasks to queue
[2025-06-23T14:04:22.447+0000] {logging_mixin.py:190} INFO - [2025-06-23T14:04:22.446+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T14:04:22.467+0000] {logging_mixin.py:190} INFO - [2025-06-23T14:04:22.466+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_tenant_process.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_tenant_process.py", line 1
    using System;
          ^^^^^^
SyntaxError: invalid syntax
[2025-06-23T14:04:22.469+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T14:04:22.500+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_tenant_process.py took 0.068 seconds
[2025-06-23T14:04:52.792+0000] {processor.py:186} INFO - Started process (PID=5504) to work on /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T14:04:52.794+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_tenant_process.py for tasks to queue
[2025-06-23T14:04:52.797+0000] {logging_mixin.py:190} INFO - [2025-06-23T14:04:52.797+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T14:04:52.817+0000] {logging_mixin.py:190} INFO - [2025-06-23T14:04:52.815+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_tenant_process.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_tenant_process.py", line 1
    using System;
          ^^^^^^
SyntaxError: invalid syntax
[2025-06-23T14:04:52.818+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T14:04:52.854+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_tenant_process.py took 0.071 seconds
[2025-06-23T14:05:23.407+0000] {processor.py:186} INFO - Started process (PID=5569) to work on /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T14:05:23.408+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_tenant_process.py for tasks to queue
[2025-06-23T14:05:23.412+0000] {logging_mixin.py:190} INFO - [2025-06-23T14:05:23.411+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T14:05:23.431+0000] {logging_mixin.py:190} INFO - [2025-06-23T14:05:23.429+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_tenant_process.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_tenant_process.py", line 1
    using System;
          ^^^^^^
SyntaxError: invalid syntax
[2025-06-23T14:05:23.432+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T14:05:23.464+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_tenant_process.py took 0.067 seconds
[2025-06-23T14:05:54.355+0000] {processor.py:186} INFO - Started process (PID=5634) to work on /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T14:05:54.360+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_tenant_process.py for tasks to queue
[2025-06-23T14:05:54.371+0000] {logging_mixin.py:190} INFO - [2025-06-23T14:05:54.370+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T14:05:54.411+0000] {logging_mixin.py:190} INFO - [2025-06-23T14:05:54.407+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_tenant_process.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_tenant_process.py", line 1
    using System;
          ^^^^^^
SyntaxError: invalid syntax
[2025-06-23T14:05:54.412+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_tenant_process.py
[2025-06-23T14:05:54.475+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_tenant_process.py took 0.149 seconds
